# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v6-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            # Needed by librosa
            sudo apt-get update
            sudo apt-get install libsndfile1-dev ffmpeg
            # use latest version for following packages
            pip install --progress-bar off -U pip setuptools julius
            pip install --use-deprecated=legacy-resolver --progress-bar off -U git+https://github.com/facebookincubator/submitit@main#egg=submitit
            pip install --use-deprecated=legacy-resolver --progress-bar off  -U git+https://git@github.com/facebookresearch/dora@main#egg=dora-search
            # use cache if available for all others
            pip install numpy
            pip install --use-deprecated=legacy-resolver --progress-bar off -r requirements.txt
            python -m spacy download nl_core_news_sm --progress-bar off
            python -m spacy download nl_core_news_md --progress-bar off

      - save_cache:
          paths:
            - ./venv
          key: v6-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: print information
          when: always
          command: |
            . venv/bin/activate
            pip freeze

      - run:
          name: mypy
          when: always
          command: |
            . venv/bin/activate
            mypy bm
      - run:
          name: flake8
          when: always
          command: |
            . venv/bin/activate
            flake8 bm
      - run:
          name: pytest
          when: always
          command: |
            export USER=johndoe
            . venv/bin/activate
            pytest bm -v --durations=20 --cov=bm
